[phases.setup]
nixPkgs = ["nodejs_24"]
aptPkgs = ["curl", "wget"]

[phases.install]
cmds = [
	"npm exec --yes pnpm@11.6.0 -- pnpm i --frozen-lockfile --config.engine-strict=false",
]

[phases.build]
cmds = ["npm exec --yes pnpm@11.6.0 -- pnpm run build"]

[start]
cmd = "npm exec --yes pnpm@11.6.0 -- pnpm run start"
